name: Run Smoke Tests on deployment

on:
  push:
    branches:
      - master
      - driver_factory
permissions:
  contents: write

jobs:

  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Run Smoke Tests
      run:  dotnet test --logger "trx;LogFileName=TestResults.trx" --results-directory allure-results --filter "Category=Smoke"

      env:
       DOTNET_ENVIRONMENT: Test

    - name: List allure-results directory contents
      run: ls -la allure-results
     # Determine the next directory number
    - name: Determine next directory number
      id: next_dir
      run: |
         # List existing directories in allure-history
         dirs=$(ls gh-pages/allure-history)
         # Find the highest number and increment it
         next_dir=$(echo "$dirs" | awk -F'/' '{print $NF}' | sort -n | tail -n 1)
         next_dir=$((next_dir + 1))
         echo "Next directory number: $next_dir"
         echo "next_dir=$next_dir" >> $GITHUB_ENV



    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: allure-results


    - name: List Screenshots Directory
      run: |
        echo "Listing contents of $(pwd):"
        ls -al
        echo "Listing contents of Screenshots directory:"
        screenshots_dir="${{github.workspace}}/Screenshots"
        echo "Full path to Screenshots directory: $screenshots_dir"
        ls -al "$screenshots_dir"

    - name: Upload Screenshots
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: screenshots
        path: ${{github.workspace}}/Screenshots
        if-no-files-found: ignore
    
    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: gh-pages

    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_report: allure-report
        gh_pages: gh-pages
        allure_history: allure-history
        keep_reports: 20
     # Copy the history folder to the new directory
    - name: Copy history to new directory
      run: |
        cp -r allure-results/history/* gh-pages/${{ env.next_dir }}/history/

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history